### ISSUE TITLE
duplicated MB1 convention edition data

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#27]
there seems to be duplicated information for MB1

`CMB1` has "Mystery Booster Booster Box Convention Edition 2021" with a proper tcg identifier
`MB1` has "Mystery Booster Booster Box (Convention Edition - 2021)" with no identifier

same goes for packs

i think logically they belong to MB1 but they got put in CMB1 because of the playtest cards maybe?

**Comment by axxroytovu** [comment]
This is an issue with the parent data. 

We're pulling data from both TCGPlayer and Card Kingdom, and they don't always put products in the same set. 

It looks like TCGPlayer has it in CMB1, and Card Kingdom has it in MB1. I don't have a good way to manually change that right now besides reaching out to the upstream and seeing if they can update the data.

**Comment by kodawah** [comment]
perhaps we can make a list of redundant sealed product and skip some, manually adding the identifiers as needed?

**Comment by axxroytovu** [comment]
That could be a reasonable approach. It would need to be done in MTGJson, since it's modifying the data directly from the upstream sources. You should open an issue there and work with Zach to determine the best path forward. I'm happy to do data entry as needed but I don't have the capacity to build the framework right now.

**Comment by kodawah** [comment]
moving to https://github.com/mtgjson/mtgjson/issues/1102
